services:
  coad:
    build: .

    ports:
      - "3000:3000"

    volumes:
      - ubuntu_lunar_home:/home/user
      - ./cs362-coad-resources:/home/user/cs362-coad-resources
      - ./cs362-cold-beverages-Wi2024:/home/user/cs362-cold-beverages-Wi2024

    stdin_open: true
    tty: true

volumes:
  ubuntu_lunar_home: {}
